markdown: rdiscount
highlighter: pygments
pygments: true
permalink: /:title.html
name: "PlanetBlue"
author: "PlanetBlue"
atom-baseurl: "http://lixiangqian.com"
disqus: "sylviayoung"
favicon: /favicon.ico
