markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
permalink: /:title.html
name: "PlanetBlue"
author: "PlanetBlue"
atom-baseurl: "http://lixiangqian.com"
disqus: "sylviayoung"
favicon: /favicon.ico
